version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Japan
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
